"use client";

/**
 * VerifyChecklist — sticky sidebar on the coach intake form rendering the
 * `verify_in_session` questions the intake-insights Haiku call generated.
 *
 * Flow:
 *   1. Client fills the intake questionnaire on their phone.
 *   2. Haiku writes ~5 questions to Client.intake_insights.verify_in_session —
 *      gaps / ambiguities / sensitive areas the AI thinks Shivani can only
 *      get a real answer to in person.
 *   3. Coach opens /clients-v2/[id]/analyse/intake to do the actual intake
 *      call. This component pins those questions in a sidebar.
 *   4. As coach asks each one, she ticks "asked" + types the client's
 *      answer in-line.
 *   5. On session save, the IntakeForm reads `getNotesBlock()` and appends
 *      it as a labelled section into the session's coach_notes — so the
 *      Q+A audit trail lives forever on the session record.
 *
 * State is exposed via the `useVerifyChecklist` hook so the parent
 * IntakeForm can read responses at submit time.
 */

import { useState } from "react";

export interface VerifyResponse {
  asked: boolean;
  answer: string;
}

export interface VerifyChecklistState {
  questions: string[];
  responses: Record<number, VerifyResponse>;
  toggle: (i: number) => void;
  setAnswer: (i: number, text: string) => void;
  /**
   * Build the labelled block to append into session.coach_notes on save.
   * Returns "" when nothing was asked (so the section is silently dropped).
   */
  getNotesBlock: () => string;
}

export function useVerifyChecklist(initial: string[]): VerifyChecklistState {
  const [responses, setResponses] = useState<Record<number, VerifyResponse>>({});

  const toggle = (i: number) => {
    setResponses((prev) => ({
      ...prev,
      [i]: {
        asked: !(prev[i]?.asked ?? false),
        answer: prev[i]?.answer ?? "",
      },
    }));
  };

  const setAnswer = (i: number, text: string) => {
    setResponses((prev) => ({
      ...prev,
      [i]: {
        asked: prev[i]?.asked ?? true,
        answer: text,
      },
    }));
  };

  const getNotesBlock = (): string => {
    const lines: string[] = [];
    for (let i = 0; i < initial.length; i++) {
      const r = responses[i];
      if (!r) continue;
      if (!r.asked && !r.answer.trim()) continue;
      const mark = r.asked ? "✓" : "○";
      const ans = r.answer.trim();
      lines.push(`${mark} Q: ${initial[i]}`);
      if (ans) lines.push(`  A: ${ans}`);
    }
    if (lines.length === 0) return "";
    return "Verify-in-session Q&A (AI-prompted):\n" + lines.join("\n");
  };

  return { questions: initial, responses, toggle, setAnswer, getNotesBlock };
}

interface Props {
  state: VerifyChecklistState;
  modelLabel?: string;        // e.g. "claude-haiku-4-5 · 14 May 09:30"
  emptyHint?: string;         // e.g. "No insights generated yet"
}

export function VerifyChecklist({
  state,
  modelLabel,
  emptyHint = "No verify-in-session questions yet — generate insights from the client overview first.",
}: Props) {
  const { questions, responses, toggle, setAnswer } = state;
  const askedCount = Object.values(responses).filter((r) => r.asked).length;

  if (questions.length === 0) {
    return (
      <aside
        aria-label="AI verify-in-session questions"
        style={{
          padding: 14,
          borderRadius: 8,
          background: "rgba(141, 153, 174, 0.06)",
          border: "1px dashed rgba(141, 153, 174, 0.3)",
          fontSize: 12,
          color: "var(--fg-3, #8D99AE)",
          lineHeight: 1.5,
        }}
      >
        {emptyHint}
      </aside>
    );
  }

  return (
    <aside
      aria-label="AI verify-in-session questions"
      style={{
        padding: 14,
        borderRadius: 8,
        background: "rgba(43, 45, 66, 0.04)",
        border: "1px solid rgba(43, 45, 66, 0.12)",
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "baseline",
          justifyContent: "space-between",
          gap: 6,
          marginBottom: 10,
        }}
      >
        <div style={{ fontSize: 11.5, color: "var(--fg-2)", textTransform: "uppercase", letterSpacing: "0.05em", fontWeight: 600 }}>
          🎯 Ask in this session
        </div>
        <span style={{ fontSize: 11, color: "var(--fg-3)" }}>
          {askedCount}/{questions.length}
        </span>
      </div>
      {modelLabel && (
        <div style={{ fontSize: 10.5, color: "var(--fg-3)", marginBottom: 10, fontStyle: "italic" }}>
          generated by {modelLabel}
        </div>
      )}
      <ol style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 10 }}>
        {questions.map((q, i) => {
          const r = responses[i] ?? { asked: false, answer: "" };
          return (
            <li
              key={i}
              style={{
                padding: 10,
                borderRadius: 6,
                background: "white",
                border: r.asked ? "1px solid rgba(5, 150, 105, 0.4)" : "1px solid rgba(141, 153, 174, 0.2)",
                opacity: r.asked && !r.answer.trim() ? 0.85 : 1,
              }}
            >
              <button
                type="button"
                onClick={() => toggle(i)}
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: 8,
                  background: "transparent",
                  border: 0,
                  padding: 0,
                  width: "100%",
                  textAlign: "left",
                  cursor: "pointer",
                  fontSize: 13,
                  lineHeight: 1.45,
                  color: "var(--fg-1)",
                  textDecoration: r.asked ? "line-through" : "none",
                  textDecorationColor: "rgba(5, 150, 105, 0.6)",
                }}
                aria-pressed={r.asked}
                aria-label={r.asked ? `Mark as not asked: ${q}` : `Mark as asked: ${q}`}
              >
                <span
                  aria-hidden
                  style={{
                    width: 16,
                    height: 16,
                    flex: "0 0 auto",
                    marginTop: 2,
                    borderRadius: 3,
                    border: r.asked ? "1.5px solid #059669" : "1.5px solid var(--lavender)",
                    background: r.asked ? "#059669" : "transparent",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "white",
                    fontSize: 11,
                    fontWeight: 700,
                  }}
                >
                  {r.asked && "✓"}
                </span>
                <span style={{ flex: 1, minWidth: 0 }}>{q}</span>
              </button>
              {r.asked && (
                <textarea
                  value={r.answer}
                  onChange={(e) => setAnswer(i, e.target.value)}
                  placeholder="Type her answer…"
                  rows={2}
                  style={{
                    marginTop: 8,
                    width: "100%",
                    boxSizing: "border-box",
                    fontFamily: "inherit",
                    fontSize: 12.5,
                    lineHeight: 1.5,
                    padding: "6px 8px",
                    borderRadius: 4,
                    border: "1px solid rgba(141, 153, 174, 0.3)",
                    background: "var(--bone-warm, #EFEAE8)",
                    color: "var(--fg-1)",
                    resize: "vertical",
                    outline: "none",
                  }}
                  onFocus={(e) => {
                    e.target.style.borderColor = "var(--indigo, #2B2D42)";
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = "rgba(141, 153, 174, 0.3)";
                  }}
                />
              )}
            </li>
          );
        })}
      </ol>
      <div style={{ marginTop: 10, fontSize: 11, color: "var(--fg-3)", fontStyle: "italic", lineHeight: 1.5 }}>
        Tap to mark asked + jot her answer. Saved into session notes when you submit.
      </div>
    </aside>
  );
}
