#!/usr/bin/env python3
"""Scan every client under ~/fm-plans/clients/, find fragmented WhatsApp
rolling-thread sessions, and consolidate each client's fragments into one
session file ordered chronologically.

Idempotent — safe to re-run. If a client has 0 or 1 whatsapp-tagged
session, nothing happens for them.

The merge logic itself lives in `merge-whatsapp-thread.py`; this script just
locates the targets and invokes the merge per client.

Background: a timezone bug in active-plan-slug.ts (fixed in commit b71bb52,
2026-05-18) caused the `[window: …]` marker to differ between IST and UTC
hosts. Sessions appended via the IST-local PM2 coach process didn't match
the marker generated by the UTC-local Fly intake receiver → save-session.py
created a new file instead of appending. This script cleans up the
historical fragmentation that resulted.

Usage:
  python scripts/consolidate-whatsapp-threads.py            # dry-run (default — reports only)
  python scripts/consolidate-whatsapp-threads.py --apply    # actually merge

Each client's canonical marker is derived from the NEWEST session file's
marker — that's the format the system is currently emitting, which after the
fix will be the timezone-stable form.
"""
from __future__ import annotations
import os
import re
import sys
import subprocess
from pathlib import Path

PLANS_ROOT = Path(os.environ.get("FMDB_PLANS_DIR", str(Path.home() / "fm-plans")))
CLIENTS_DIR = PLANS_ROOT / "clients"
MERGER = Path(__file__).resolve().parent / "merge-whatsapp-thread.py"

WHATSAPP_TAG = "[source: whatsapp_"
MARKER_RE = re.compile(r"(\[plan:\s*[^\]]+\])(\s*\[window:\s*[0-9-]+\])?")


def find_whatsapp_files(sessions_dir: Path):
    """Return list of session files containing a whatsapp source tag."""
    out = []
    if not sessions_dir.is_dir():
        return out
    for f in sorted(sessions_dir.glob("*.yaml")):
        try:
            text = f.read_text()
        except Exception:
            continue
        if WHATSAPP_TAG in text:
            out.append(f)
    return out


def canonical_marker(latest_file: Path):
    """Pick the marker from the most-recently-modified WA file. That's the
    one the live system is emitting today; after the b71bb52 fix it's also
    timezone-stable."""
    text = latest_file.read_text()
    m = MARKER_RE.search(text)
    if not m:
        return None
    plan = m.group(1).strip()
    window = (m.group(2) or "").strip()
    return f"{plan} {window}".strip()


def main():
    apply = "--apply" in sys.argv

    if not CLIENTS_DIR.exists():
        print(f"clients dir not found: {CLIENTS_DIR}")
        sys.exit(1)

    total_fragmented = 0
    total_merged = 0

    for client_dir in sorted(CLIENTS_DIR.iterdir()):
        if not client_dir.is_dir():
            continue
        sessions_dir = client_dir / "sessions"
        files = find_whatsapp_files(sessions_dir)
        if len(files) < 2:
            continue

        # Sort by mtime so the newest is last (canonical marker source)
        # but pick the OLDEST as the merge target (keeps stable session_id).
        files_by_mtime = sorted(files, key=lambda p: p.stat().st_mtime)
        oldest = files_by_mtime[0]
        newest = files_by_mtime[-1]
        marker = canonical_marker(newest) or canonical_marker(oldest)
        if not marker:
            print(f"  {client_dir.name}: ERROR — couldn't extract marker from any file, skipping")
            continue

        total_fragmented += 1
        print(f"{client_dir.name}: {len(files)} whatsapp files → merge into {oldest.name}  marker={marker}")
        if not apply:
            for f in files:
                print(f"    - {f.name}")
            continue

        # Invoke merger. It writes into `oldest` then we delete the rest.
        cmd = [
            sys.executable, str(MERGER), marker, str(oldest),
            *(str(p) for p in files),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"    ERROR: {result.stderr.strip() or result.stdout.strip()}")
            continue
        print(f"    {result.stdout.strip()}")
        for f in files:
            if f != oldest:
                f.unlink(missing_ok=True)
                print(f"    deleted {f.name}")
        total_merged += 1

    if not apply:
        print()
        if total_fragmented == 0:
            print("[scan] no clients with fragmented threads. System is clean.")
        else:
            print(f"[scan] {total_fragmented} client(s) need merging. Re-run with --apply.")
    else:
        print()
        print(f"[merge] merged {total_merged} of {total_fragmented} fragmented clients.")


if __name__ == "__main__":
    main()
