/**
 * Traced two-pose exercise figures — the real artwork, where it exists.
 *
 * The deterministic stick figure in exercise-figure.ts stays as the fallback:
 * it is computed from catalogue fields so every entry gets SOMETHING, and it
 * can never disagree with the safety axes beside it. This module serves the
 * hand-reviewed traced pairs (generated one image per pose, traced, registered
 * by maximum overlap) from fm-database/data/_exercise_figures.json, and the
 * caller falls back to the stick figure when a slug has no traced art yet.
 *
 * Server-only: reads the asset off disk the same way client-app.ts reads the
 * catalogue. Everything fails CLOSED — a missing file, unparseable JSON, or a
 * malformed entry yields null, never a broken figure.
 */
import fs from "node:fs";
import path from "node:path";

import { getCataloguePath } from "./paths";

interface TracedFrame {
  x0: number;
  x1: number;
  y0: number;
  y1: number;
  /** Registered offset onto frame 0 — only present on cycle figures. */
  dx?: number;
  dy?: number;
  /** SVG path `d` strings, generated by our own tracer — no free text. */
  paths: string[];
}

/**
 * A motion arrow drawn over the figure, in the frames' own coordinate space.
 *
 * Two poses can be perfectly drawn and still not say which WAY the movement
 * goes: a sideways hop cross-fades between a figure left of a line and the same
 * figure right of it, which reads as a jump-cut rather than a hop. The coach
 * asked for arrows on exactly that one (2026-08-05), and it generalises to any
 * figure whose direction is not self-evident.
 *
 * `bow` curves the arrow: it is the perpendicular offset of the quadratic
 * control point from the straight line, so a hop arcs the way a hop actually
 * travels. Zero or absent is a straight arrow.
 */
interface TracedArrow {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  bow?: number;
}

export interface TracedFigure {
  name: string;
  cue: string;
  muscle: string;
  source: string;
  frames: TracedFrame[];
  /** Translation that sits frame B on frame A (max-ink-overlap registration). */
  reg: [number, number];
  /** Direction-of-travel arrows, drawn over every frame. */
  arrows?: TracedArrow[];
}

let cache: Record<string, TracedFigure> | null | undefined;

function isFrame(f: unknown): f is TracedFrame {
  if (typeof f !== "object" || f === null) return false;
  const d = f as Record<string, unknown>;
  return (
    [d.x0, d.x1, d.y0, d.y1].every((v) => typeof v === "number" && Number.isFinite(v)) &&
    [d.dx, d.dy].every((v) => v === undefined || (typeof v === "number" && Number.isFinite(v))) &&
    Array.isArray(d.paths) &&
    d.paths.length > 0 &&
    d.paths.every((p) => typeof p === "string" && /^[MLZmlz0-9.,\-\s]+$/.test(p))
  );
}

function isArrow(a: unknown): a is TracedArrow {
  if (typeof a !== "object" || a === null) return false;
  const d = a as Record<string, unknown>;
  return (
    [d.x1, d.y1, d.x2, d.y2].every((v) => typeof v === "number" && Number.isFinite(v)) &&
    (d.bow === undefined || (typeof d.bow === "number" && Number.isFinite(d.bow)))
  );
}

function load(): Record<string, TracedFigure> {
  if (cache !== undefined && cache !== null) return cache;
  const file = path.join(getCataloguePath(), "_exercise_figures.json");
  try {
    const raw = JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
    const out: Record<string, TracedFigure> = {};
    for (const [slug, v] of Object.entries(raw)) {
      if (typeof v !== "object" || v === null) continue;
      const e = v as Record<string, unknown>;
      const frames = Array.isArray(e.frames) ? e.frames.filter(isFrame) : [];
      const reg = Array.isArray(e.reg) ? e.reg : [];
      if (frames.length < 2) continue;
      if (reg.length !== 2 || !reg.every((n) => typeof n === "number" && Number.isFinite(n))) continue;
      if (frames.length > 12) continue;
      // Arrows are decoration: a malformed one is dropped on its own rather
      // than costing the figure it annotates.
      const arrows = Array.isArray(e.arrows) ? e.arrows.filter(isArrow).slice(0, 6) : [];
      out[slug] = {
        name: typeof e.name === "string" ? e.name : slug,
        cue: typeof e.cue === "string" ? e.cue : "",
        muscle: typeof e.muscle === "string" ? e.muscle : "",
        source: typeof e.source === "string" ? e.source : "",
        frames,
        reg: [reg[0], reg[1]] as [number, number],
        ...(arrows.length ? { arrows } : {}),
      };
    }
    cache = out;
  } catch {
    cache = {};
  }
  return cache;
}

export function hasTracedFigure(slug: string): boolean {
  return Boolean(load()[slug]);
}

/** Exposed for tests only. */
export function _resetTracedFigureCache(): void {
  cache = undefined;
}

/**
 * A self-contained animated SVG. Two frames cross-fade start↔end after
 * registration; three or more play as a registered cycle (the coach reviewed
 * and approved the multi-stage routines in exactly this form). Colours ride on
 * CSS custom properties so the figure themes with its host; reduced-motion
 * shows the first pose alone. Returns null when the slug has no traced art —
 * the caller renders the deterministic stick figure instead.
 */
export function tracedFigureSvg(slug: string, opts: { title?: string } = {}): string | null {
  const fig = load()[slug];
  if (!fig) return null;
  const frames = fig.frames;
  // Two-pose figures register frame B by `reg`; cycles carry per-frame dx/dy.
  const off = (f: TracedFrame, i: number): [number, number] =>
    frames.length === 2 && i === 1 ? fig.reg : [f.dx ?? 0, f.dy ?? 0];

  let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity;
  frames.forEach((f, i) => {
    const [dx, dy] = off(f, i);
    x0 = Math.min(x0, f.x0 + dx); x1 = Math.max(x1, f.x1 + dx);
    y0 = Math.min(y0, f.y0 + dy); y1 = Math.max(y1, f.y1 + dy);
  });
  // An arrow outside the figures' bounds would be silently clipped, which is
  // worse than no arrow — the reader sees a stub pointing off the edge.
  for (const a of fig.arrows ?? []) {
    const [cx, cy] = arrowControl(a);
    x0 = Math.min(x0, a.x1, a.x2, cx); x1 = Math.max(x1, a.x1, a.x2, cx);
    y0 = Math.min(y0, a.y1, a.y2, cy); y1 = Math.max(y1, a.y1, a.y2, cy);
  }
  const pad = 0.03;
  const vb = `${(x0 - (x1 - x0) * pad).toFixed(0)} ${(y0 - (y1 - y0) * pad).toFixed(0)} ${((x1 - x0) * (1 + 2 * pad)).toFixed(0)} ${((y1 - y0) * (1 + 2 * pad)).toFixed(0)}`;

  // The slug is catalogue-validated, but the animation name must be a CSS
  // identifier regardless of what is on disk.
  const key = slug.replace(/[^a-zA-Z0-9]/g, "");
  const label = escapeAttr(opts.title ?? `${fig.name} — start and end positions`);
  const p = (frame: TracedFrame) => frame.paths.map((d) => `<path d="${d}"/>`).join("");

  let css: string;
  if (frames.length === 2) {
    css =
      `@keyframes tfA${key}{0%,38%{opacity:1}50%,88%{opacity:0}100%{opacity:1}}` +
      `@keyframes tfB${key}{0%,38%{opacity:0}50%,88%{opacity:1}100%{opacity:0}}` +
      `.fm-traced-figure .tf0{animation:tfA${key} var(--fm-fig-cyc,4s) ease-in-out infinite}` +
      `.fm-traced-figure .tf1{animation:tfB${key} var(--fm-fig-cyc,4s) ease-in-out infinite}`;
  } else {
    // Each frame owns an equal slot of the cycle with a short fade at its
    // edges; the cycle duration scales with frame count so pace stays steady.
    const n = frames.length;
    const cyc = `var(--fm-fig-cyc,${Math.round(n * 1.4)}s)`;
    const parts: string[] = [];
    for (let i = 0; i < n; i++) {
      const a = (100 * i) / n;
      const b = (100 * (i + 1)) / n;
      const fade = Math.min(3.5, (b - a) / 4);
      const kf = i === 0
        ? `@keyframes tf${key}${i}{0%{opacity:1}${fade.toFixed(2)}%,${(b - fade).toFixed(2)}%{opacity:1}${b.toFixed(2)}%,${(100 - fade).toFixed(2)}%{opacity:0}100%{opacity:1}}`
        : `@keyframes tf${key}${i}{0%,${(a - 0.01).toFixed(2)}%{opacity:0}${(a + fade).toFixed(2)}%,${(b - fade).toFixed(2)}%{opacity:1}${Math.min(100, b).toFixed(2)}%,100%{opacity:0}}`;
      parts.push(kf, `.fm-traced-figure .tf${i}{animation:tf${key}${i} ${cyc} linear infinite}`);
    }
    css = parts.join("");
  }
  const gs = frames
    .map((f, i) => {
      const [dx, dy] = off(f, i);
      const t = dx || dy ? ` transform="translate(${dx.toFixed(1)},${dy.toFixed(1)})"` : "";
      return `<g class="tf${i}"${t}>${p(f)}</g>`;
    })
    .join("");

  const arrows = fig.arrows ?? [];
  // Sized off the figure so an arrow reads the same on a tall side-view and a
  // wide plank; a fixed stroke width would vanish on one and dominate the other.
  const unit = Math.max(1, Math.hypot(x1 - x0, y1 - y0) / 100);
  const arrowSvg = arrows.length
    ? `<defs><marker id="tfah${key}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">` +
      `<path d="M2 1L8 5L2 9" fill="none" stroke="context-stroke" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></marker></defs>` +
      arrows
        .map((a) => {
          const [cx, cy] = arrowControl(a);
          // pathLength normalises the curve to 100 units, so the draw-on
          // animation below needs no arc-length maths and is exact for any
          // arrow shape.
          return `<path class="tfarr" pathLength="100" d="M${a.x1.toFixed(1)},${a.y1.toFixed(1)}Q${cx.toFixed(1)},${cy.toFixed(1)} ${a.x2.toFixed(1)},${a.y2.toFixed(1)}" marker-end="url(#tfah${key})"/>`;
        })
        .join("")
    : "";

  // The arrow DRAWS ITSELF along its path, in step with the pose it explains:
  // hidden while the start pose holds, drawing through the cross-fade window
  // (38%-50%, matching tfA/tfB above), holding while the end pose is up, then
  // clearing before the cycle restarts. A static arrow says which way; a drawn
  // one says the movement happens now, which is what a hop needs.
  //
  // Opacity does the hiding, not the dash offset alone: an SVG marker is drawn
  // at its vertex regardless of dashing, so a fully-offset stroke would still
  // leave the arrowhead sitting there on its own.
  const arrowCss = arrows.length
    ? `@keyframes tfar${key}{0%,34%{stroke-dashoffset:100;opacity:0}38%{stroke-dashoffset:100;opacity:1}` +
      `52%,84%{stroke-dashoffset:0;opacity:1}94%,100%{stroke-dashoffset:0;opacity:0}}` +
      `.fm-traced-figure .tfarr{stroke-dasharray:100;stroke-dashoffset:100;` +
      `animation:tfar${key} var(--fm-fig-cyc,4s) ease-in-out infinite}`
    : "";

  return `<svg viewBox="${vb}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${label}" class="fm-traced-figure">
<style>
.fm-traced-figure{width:100%;height:auto}
/* Scoped to frame paths only. An unscoped path rule also hits the arrowhead in
   the marker def, and a CSS rule beats that path's inline fill attribute, so the
   head filled solid grey and read as a blob rather than a chevron.
   NOTE: no angle-bracketed tag names in this comment. SVG is XML, so a literal
   tag name inside a style element is parsed as markup and the whole image fails
   to render — which is exactly how this comment broke it the first time. */
.fm-traced-figure g > path{fill:var(--fm-fig,#A9A395);stroke:var(--fm-figline,#4F4D45);stroke-width:1.3;stroke-opacity:.42}
${arrows.length ? `.fm-traced-figure .tfarr{fill:none;stroke:var(--fm-fig-arrow,#C0392B);stroke-width:${(unit * 1.6).toFixed(2)};stroke-opacity:1;stroke-linecap:round}\n${arrowCss}\n` : ""}${css}
@media (prefers-reduced-motion:reduce){.fm-traced-figure g{animation:none!important;opacity:0}.fm-traced-figure .tf0{opacity:1}${arrows.length ? ".fm-traced-figure .tfarr{animation:none!important;stroke-dashoffset:0;opacity:1}" : ""}}
</style>
${gs}${arrowSvg}
</svg>`;
}

/** Quadratic control point for an arrow's `bow`, perpendicular to its chord. */
function arrowControl(a: TracedArrow): [number, number] {
  const mx = (a.x1 + a.x2) / 2;
  const my = (a.y1 + a.y2) / 2;
  const bow = a.bow ?? 0;
  if (!bow) return [mx, my];
  const dx = a.x2 - a.x1;
  const dy = a.y2 - a.y1;
  const len = Math.hypot(dx, dy) || 1;
  // Perpendicular, doubled: a quadratic curve reaches only half way to its
  // control point, so the drawn arc rises by `bow`, not by half of it.
  return [mx + (-dy / len) * bow * 2, my + (dx / len) * bow * 2];
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
