/**
 * The client app's somatic matcher must agree with the coach's, exactly.
 *
 * The coach reads chief complaints through `fmdb/assess/somatic_read.py`; the
 * client app cannot shell out, so `somatic-read.ts` duplicates it. Two copies
 * of a matcher drift, and the drift is invisible — the coach sees one reading
 * on her screen and the client sees another, or none.
 *
 * So this pins the TS against output captured from the REAL Python, running
 * over the REAL catalogue. `__fixtures__/somatic-read-python.json` is
 * regenerated by hand when the matcher legitimately changes; if the two ever
 * disagree, one of them is wrong and this fails.
 *
 * The fixture conditions are synthetic on purpose. A client's real condition
 * list is PHI and does not belong in the repo.
 */
import { describe, it, expect } from "vitest";

import fixture from "./__fixtures__/somatic-read-python.json";
import { conditionPhrases, isClientSafe, readChiefComplaints } from "./somatic-read";

const reads = readChiefComplaints(fixture.conditions);

describe("TS matcher agrees with the Python one", () => {
  it("finds the same maps, for the same conditions, in the same order", () => {
    expect(reads.map((r) => [r.condition, r.targetSlug, r.mapSlug])).toEqual(
      fixture.reads.map((r) => [r.condition, r.targetSlug, r.mapSlug]),
    );
  });

  it("agrees on sensitivity and gating for every one of them", () => {
    expect(reads.map((r) => [r.sensitivity, r.gated, isClientSafe(r)])).toEqual(
      fixture.reads.map((r) => [r.sensitivity, r.gated, r.clientSafe]),
    );
  });

  it("carries the same reframe, question and practice", () => {
    expect(reads.map((r) => [r.reframe, r.inquiryQuestion, r.somaticPractice])).toEqual(
      fixture.reads.map((r) => [r.reframe, r.inquiryQuestion, r.somaticPractice]),
    );
  });

  it("agrees on the emotional roots — these are the reading itself", () => {
    expect(reads.map((r) => r.roots)).toEqual(fixture.reads.map((r) => r.roots));
  });

  /* Guards the fixture rather than the code: a fixture that matched nothing,
     or everything, would let the three tests above pass while proving nothing. */
  it("the fixture actually exercises both outcomes", () => {
    expect(reads.length).toBeGreaterThan(6);
    expect(reads.filter(isClientSafe).length).toBeGreaterThan(2);
    expect(reads.filter((r) => !isClientSafe(r)).length).toBeGreaterThan(2);
    expect(reads.some((r) => r.gated)).toBe(true);
    expect(fixture.conditions.length).toBeGreaterThan(reads.length); // some must MISS
  });
});

describe("conditionPhrases — how a free-text condition becomes lookup keys", () => {
  it("takes the clinical head off a decorated entry", () => {
    expect(
      conditionPhrases("Hypertension — ON TREATMENT (previously unreported) — Telma 40 twice daily"),
    ).toEqual(["hypertension"]);
  });

  it("drops clinically empty words rather than matching on them", () => {
    expect(conditionPhrases("Chronic mild anxiety")).toEqual(["anxiety"]);
    expect(conditionPhrases("Type 2 diabetes — HbA1c 6.6%")).not.toContain("type");
  });

  it("offers the trailing noun as well as the whole head", () => {
    const keys = conditionPhrases("Knee Injury / weak tendons");
    expect(keys[0]).toBe("knee-injury");
    expect(keys).toContain("injury");
    expect(keys).toContain("knee");
  });

  it("drops keys of 1-2 chars, which match noisily", () => {
    expect(conditionPhrases("PC")).toEqual([]);
    expect(conditionPhrases("IBS")).toEqual(["ibs"]);
  });

  it("is empty for an empty condition rather than throwing", () => {
    expect(conditionPhrases("")).toEqual([]);
    expect(conditionPhrases("   ")).toEqual([]);
  });
});

describe("the alias trap that ruled out a cheaper index", () => {
  /* `hypertension` is BOTH a somatic-map target AND an alias of
     high-blood-pressure. Resolving only map targets (rather than the whole
     catalogue) sends it to the wrong map. Eleven targets have this shape. */
  it("resolves hypertension the way the full catalogue does, not the way a map-only index would", () => {
    const [hit] = readChiefComplaints(["Hypertension"]);
    expect(hit.targetSlug).toBe("high-blood-pressure");
  });

  it("still matches the other clash targets", () => {
    for (const c of ["Migraine", "Asthma", "Palpitations"]) {
      expect(readChiefComplaints([c]), `${c} stopped resolving`).toHaveLength(1);
    }
  });
});

describe("what must never reach a client", () => {
  it("marks coach-only entries unsafe", () => {
    for (const c of ["Endometriosis", "Fibroids"]) {
      const [r] = readChiefComplaints([c]);
      expect(isClientSafe(r), `${c} would have been shown`).toBe(false);
    }
  });

  it("marks a gated entry unsafe even when its sensitivity is not coach_only", () => {
    const [r] = readChiefComplaints(["Migraine"]);
    expect(r.gated).toBe(true);
    expect(isClientSafe(r)).toBe(false);
  });

  it("never reports a read for a condition the book does not cover", () => {
    expect(readChiefComplaints(["Elevated Lp(a)"])).toEqual([]);
  });

  it("does not double-match one condition onto two maps", () => {
    const slugs = reads.map((r) => r.mapSlug);
    expect(new Set(slugs).size).toBe(slugs.length);
  });
});
